secondproject/secondproject/urls.py
from django.contrib import admin
from django.urls import path
import blog.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog.views.home, name='home'),
    path('blog/<int:pk>', blog.views.blog_detail, name = 'blog_detail'),
    path('blog/new', blog.views.blog_create, name = 'blog_new'),
    path('blog/delete/<int:pk>', blog.views.blog_delete, name = 'blog_delete'),
    path('blog/update/<int:pk>', blog.views.blog_update, name = 'blog_update'),
]

secondproject/account/models.py
from django.db import models

# Create your models here.

secondproject/blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=50)
    pub_date = models.TimeField(auto_now_add=True)
    body = models.TextField()

    def __str__(self):
        return self.title
        
    def summary(self):
        return self.body[:100]

secondproject/blog/forms.py
from django import forms
from .models import Blog

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields =('title','body')

secondproject/account/views.py
from django.shortcuts import render

# Create your views here.

secondproject/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import BlogForm
from .models import Blog

def home(request):
    blogs = Blog.objects.all()
    return render(request, 'home.html', {'blogs':blogs})

def blog_detail(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    return render(request, 'blog_detail.html', {'blog':blog})

def blog_create(request):
    form = BlogForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("home")
    return render(request, 'blog_form.html', {'form':form})

def blog_update(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    form = BlogForm(request.POST or None, instance=blog)
    if form.is_valid():
        form.save()
        return redirect('home')
    return render(request, 'blog_form.html', {'form': form})

def blog_delete(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    if request.method == 'POST':
        blog.delete()
        return redirect('home')
    return render(request, 'blog_delete.html', {'object': blog})

secondproject/blog/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
        crossorigin="anonymous">
    <title>{% block title %}Blog{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog_new' %}">글쓰기</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <div class='container'>
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

secondproject/blog/templates/blog_delete.html
{% extends 'base.html' %}

{% block title %}삭제하기{% endblock %}

{% block content %}
<br>
<form method='post'>{% csrf_token %}
    <h1>정말로 {{ object.title }}를(을) 삭제하시겠습니까?</h1>
    <br>
    <input class='btn btn-dark' type='submit' value='삭제' />
</form>
{% endblock %}

secondproject/blog/templates/blog_detail.html
{% extends 'base.html' %}

{% block title %}{{blog.id}}번 글{% endblock %}

{% block content %}
<h1>자세한 본문</h1>
<br><br>

<h1> 제목 : {{blog.title}} </h1>
<p> 작성 날짜 : {{blog.pub_date}} </p>
<P> 자세한 본문 : {{blog.body}} </P>
<br>
<a href="{% url 'blog_update' blog.id %}" class='btn btn-dark active'>수정</a>
<a href="{% url 'blog_delete' blog.id %}" class='btn btn-dark active'>삭제</a>
{% endblock %}

secondproject/blog/templates/blog_form.html
{% extends 'base.html' %}

{% block title %}새로운 글쓰기{% endblock %}

{% block content %}
<br>
<form method="post">{% csrf_token %}
    {{ form.non_field_errors }}
    <div class="fieldWrapper">
        {{ form.title.errors }}
        <h4><label for="id_title">제목: </label></h4>
        {{ form.title }}
    </div>
    <br>
    <div class="fieldWrapper">
        {{ form.body.errors }}
        <h4><label for="id_body">본문: </label></h4>
        {{ form.body }}
    </div>
    <input class="btn btn-dark" type="submit" value="제출하기" />
</form>
<!-- <form action="{% url 'blog_new' %}"action="{% url 'blog_new' %}" method="post">
    <h4><label for='id_title'>제목 : </label></h4>
    <input id="id_title" type="text" name="title" />
    <br>
    <br>
    <h4><label for='id_body'>본문 : </label></h4>
    <textarea cols=40 rows=10 name="body"></textarea>
    <br>
    <br>
    <input class="btnbtn-dark" type="submit" value="제출하기">
</form> -->
<!-- <form method='post' action="{% url 'blog_new' %}">{{ csrf_token }}
    <h4>제목 : </h4>
    <input type="text" name="title">
    <br>
    <br>
    <h4>본문 : </h4>
    <textarea cols=40 rows=10 name="body"></textarea>
    <br>
    <br>
    <input class="btn btn-dark" type="submit" value="제출하기">
</form> -->
{% endblock %}

secondproject/blog/templates/home.html
{% extends 'base.html' %}

{% block title %} Blog {% endblock %}

{% block content %}
{% for blog in blogs %}
<div class="card">
    <div class="card-body">
        <h1 class="card-title">{{blog.title}}</h1>
        <h6 class="card-subtitle mb-2 text-muted">{{blog.pub_date}}</h6>
        <p class="card-text">{{blog.summary}}</p>
        <p><a href="{% url 'blog_detail' blog.id %}">...more</a></p>
    </div>
</div>

<br><br>
{% endfor %}
{% endblock %}